"""Add TreatmentTable and TreatmentTableEntry models.

Revision ID: 429c73c60710
Revises: 97c4b12df3b0
Create Date: 2020-07-17 13:39:29.364200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429c73c60710'
down_revision = '97c4b12df3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_table_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('treatment_id', sa.Integer(), nullable=True),
    sa.Column('treatment_table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ),
    sa.ForeignKeyConstraint(['treatment_table_id'], ['treatment_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment_table_entries')
    op.drop_table('treatment_tables')
    # ### end Alembic commands ###
