"""Add status column to Appointment model.

Revision ID: 6704d826efa2
Revises: b1be8897df3c
Create Date: 2020-07-15 10:18:20.706987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6704d826efa2'
down_revision = 'b1be8897df3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('status', sa.Enum('complete', 'incomplete'), server_default='incomplete', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'status')
    # ### end Alembic commands ###
