"""Add 'all_day' column to Appointment model.

Revision ID: b1be8897df3c
Revises: 1d8e9701ba53
Create Date: 2020-07-13 10:17:45.385468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1be8897df3c'
down_revision = '1d8e9701ba53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('all_day', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'all_day')
    # ### end Alembic commands ###
